# SPDX-License-Identifier: GPL-2.0+

DRAMC_LDS := $(DRAMC_DIR)/ddr.lds
DRAMC_INCLUDES := -I$(DRAMC_DIR)

DRAMC_OBJS := \
	head.o \
	setup.o \
	main.o \
	init.o \
	time.o \
	string.o \
	dramc.o \
	dramc_dq_dqs_cal.o \
	dramc_dle_cal.o \
	dramc_dqs_gw_cal.o \
	en7512_dramc_init.o \
	spram.o
