# SPDX-License-Identifier: GPL-2.0+
SOC_CROSS_COMPILE := mips-linux-gnu-
SOC_TRIPLE := mips-linux-gnu
SOC_ENDIAN := big
SOC_LD_EMULATION := elf32btsmip
SOC_UBOOT_OFFSET := 0x00020000
SOC_TCBOOT := y
SOC_RECOVERY_CHAINLOADER := n

SOC_BOOTEXT := n
